### ISSUE TITLE
undefined local variable or method `log_connections_count'

### ISSUE THREAD

**Issue by kv109** [elpassion/el-pomodoro-slack#13]
Happens when I type `start`. Session starts, but I don't get `session started` response.
Backtrace:
```
2017-05-29T08:46:11.610024+00:00 app[web.1]: 2017-05-29 08:46:11 - NameError - undefined local variable or method `log_connections_count' for #<Commands::StartSession:0x007f48e815e4f0>:
2017-05-29T08:46:11.610027+00:00 app[web.1]: 	/app/commands/start_session.rb:25:in `block in start_session'
2017-05-29T08:46:11.610028+00:00 app[web.1]: 	/app/user.rb:178:in `ok'
2017-05-29T08:46:11.610029+00:00 app[web.1]: 	/app/commands/start_session.rb:18:in `start_session'
2017-05-29T08:46:11.610030+00:00 app[web.1]: 	/app/commands/start_session.rb:12:in `block in call'
2017-05-29T08:46:11.610030+00:00 app[web.1]: 	/app/commands/command.rb:18:in `respond_with'
2017-05-29T08:46:11.610031+00:00 app[web.1]: 	/app/commands/start_session.rb:12:in `call'
2017-05-29T08:46:11.610038+00:00 app[web.1]: 	/app/commands.rb:16:in `handle'
2017-05-29T08:46:11.610039+00:00 app[web.1]: 	/app/events.rb:17:in `message'
2017-05-29T08:46:11.610039+00:00 app[web.1]: 	/app/bot.rb:38:in `block in <class:API>'
2017-05-29T08:46:11.610040+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
2017-05-29T08:46:11.610041+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
2017-05-29T08:46:11.610042+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
2017-05-29T08:46:11.610042+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
2017-05-29T08:46:11.610043+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
2017-05-29T08:46:11.610044+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
2017-05-29T08:46:11.610044+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
2017-05-29T08:46:11.610045+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
2017-05-29T08:46:11.610045+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
2017-05-29T08:46:11.610046+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
2017-05-29T08:46:11.610046+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
2017-05-29T08:46:11.610046+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
2017-05-29T08:46:11.610047+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
2017-05-29T08:46:11.610047+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
2017-05-29T08:46:11.610048+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
2017-05-29T08:46:11.610048+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
2017-05-29T08:46:11.610048+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
2017-05-29T08:46:11.610049+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
2017-05-29T08:46:11.610049+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
2017-05-29T08:46:11.610049+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
2017-05-29T08:46:11.610050+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
2017-05-29T08:46:11.610050+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
2017-05-29T08:46:11.610050+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
2017-05-29T08:46:11.610051+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
2017-05-29T08:46:11.610051+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
2017-05-29T08:46:11.610051+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
2017-05-29T08:46:11.610052+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
2017-05-29T08:46:11.610052+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
2017-05-29T08:46:11.610052+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
2017-05-29T08:46:11.610053+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
2017-05-29T08:46:11.610053+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
2017-05-29T08:46:11.610054+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
2017-05-29T08:46:11.610054+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
2017-05-29T08:46:11.610054+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
2017-05-29T08:46:11.610055+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
2017-05-29T08:46:11.610055+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/cascade.rb:33:in `block in call'
2017-05-29T08:46:11.610055+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/cascade.rb:24:in `each'
2017-05-29T08:46:11.610056+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/cascade.rb:24:in `call'
2017-05-29T08:46:11.610072+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/puma-3.7.1/lib/puma/configuration.rb:232:in `call'
2017-05-29T08:46:11.610073+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/puma-3.7.1/lib/puma/server.rb:578:in `handle_request'
2017-05-29T08:46:11.610090+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/puma-3.7.1/lib/puma/server.rb:415:in `process_client'
2017-05-29T08:46:11.610091+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/puma-3.7.1/lib/puma/server.rb:275:in `block in run'
2017-05-29T08:46:11.610091+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.3.0/gems/puma-3.7.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by kv109** [comment]
This shows that we need CI. I created a [ticket](https://github.com/elpassion/el-pomodoro-slack/issues/15) for that.
